--get me unique job_ids
SELECT  DISTINCT JOB_ID FROM EMPLOYEES;

--get me average salary for IT_PROG
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE JOB_ID='IT_PROG';

SELECT JOB_ID, AVG(SALARY),COUNT(*),SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

--get me job_id where their avg salary is more than 5k
SELECT JOB_ID, AVG(SALARY),COUNT(*),SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) >5000;






